# Generated by Django 4.0.6 on 2022-08-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impersonalaccount',
            old_name='parent_ac',
            new_name='p_ac',
        ),
        migrations.RenameField(
            model_name='impersonalaccount',
            old_name='type_ac',
            new_name='t_ac',
        ),
    ]
