# Generated by Django 4.0.6 on 2022-08-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0002_rename_parent_ac_impersonalaccount_p_ac_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='split',
            old_name='account',
            new_name='ac',
        ),
        migrations.RenameField(
            model_name='split',
            old_name='amount',
            new_name='am',
        ),
        migrations.RenameField(
            model_name='split',
            old_name='type_split',
            new_name='t_sp',
        ),
        migrations.RenameField(
            model_name='split',
            old_name='transaction',
            new_name='tx',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='description',
            new_name='desc',
        ),
    ]
