# Generated by Django 4.0.6 on 2022-09-03 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0004_rename_impersonalaccount_impersonalac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cat', models.CharField(blank=True, choices=[('AS', 'Asset'), ('LI', 'Liability'), ('IN', 'Income'), ('EX', 'Expense')], max_length=2)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('p_ac', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='coasc.ac')),
            ],
        ),
        migrations.AlterField(
            model_name='split',
            name='ac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coasc.ac'),
        ),
        migrations.DeleteModel(
            name='ImpersonalAc',
        ),
    ]
