# Generated by Django 4.0.6 on 2022-09-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0005_ac_alter_split_ac_delete_impersonalac'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='t_ac',
            field=models.CharField(choices=[('P', 'Personal'), ('I', 'Impersonal')], default='I', max_length=1),
            preserve_default=False,
        ),
    ]
