# Generated by Django 4.0.6 on 2022-09-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0006_ac_t_ac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
