# Generated by Django 4.0.6 on 2022-09-04 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0007_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='mem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='coasc.member'),
        ),
    ]
