# Generated by Django 4.0.6 on 2022-09-23 13:33

from django.db import migrations
import nepali_datetime
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0009_transaction_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=nepali_datetime_field.models.NepaliDateField(default=nepali_datetime.date.today),
        ),
    ]
