# Generated by Django 5.0.6 on 2024-06-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0009_transaction_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
