# Generated by Django 5.0.6 on 2024-06-30 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0010_rename_date_created_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tx_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
