# Generated by Django 5.0.6 on 2024-07-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0011_transaction_tx_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='cat',
            field=models.CharField(blank=True, choices=[('AS', 'Asset'), ('LI', 'Liability'), ('IN', 'Income'), ('EX', 'Expense')], default=None, max_length=2),
        ),
    ]
