# Generated by Django 5.0.6 on 2024-07-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0012_alter_ac_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='desc',
            field=models.TextField(),
        ),
    ]
