# Generated by Django 5.0.6 on 2024-07-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coasc', '0013_alter_transaction_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='cat',
            field=models.CharField(blank=True, choices=[('AS', 'Asset'), ('LI', 'Liability'), ('IN', 'Income'), ('EX', 'Expense')], default=None, max_length=2, null=True),
        ),
    ]
